/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"
#include "no-dep-cpp-lib.h"

std::string cpp_application::Greeter::greeting() {
    return std::string("Hello from my application!");
}

int main () {
    cpp_application::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;
    no_dep_cpp_lib::Greeter greeter2;
    std::cout << greeter2.greeting() << std::endl;
    return 0;
}
